name: Build

run-name: Build Code

on:
  push:
    branches: ['main', 'staging']

permissions:
  contents: write

concurrency:
  group: "build production"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - run: |
          npm i
          npm run build
          cd dist
          touch .nojekyll

      - name: Minify Code
        uses: Lenni009/minify-js@main
        with:
          directory: dist
          overwrite: true

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
          target-folder: staging # The folder the action should deploy to.

