name: Check PR Branch
run-name: Check PR Branch

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Check-PR-Branch:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Check Branch
        run: |
          if [[ ${{ github.head_ref }} != 'staging' && ${{ github.base_ref }} == 'main' ]]; then
            echo "Pushing to main branch is not allowed."
            exit 1
          fi

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message: 'Check failed. Please review.'
        if: ${{ github.head_ref != 'staging' && github.base_ref == 'main' && job.status == 'failure' }}